### ISSUE TITLE
In step 20 i got an error like: FileNotFoundError: [Errno 2] No such file or directory: '/content/img1.jpg'

### ISSUE THREAD

**Issue by ondereser** [Nkap23/TensorFlow_with_Colab_tutorial#3]
I get an error like in the picture. What should i do? 
![Ekran Alıntısı](https://user-images.githubusercontent.com/64664269/101281492-30735980-37e0-11eb-84a1-3ba53bd3608e.PNG)

**Comment by Nkap23** [comment]
Hello! Check for the path of the image you uploaded! Most likely there is no image present at '/content/img1.jpg' (according to the error message)

**Comment by ondereser** [comment]
I fixed the problem, but then i got a **NameError: name 'detect_fn' is not defined**, in step 20.

**Comment by Nkap23** [comment]
'detect_fn' is used in step 17 to load the saved model and build the detection function

# Load saved model and build the detection function
detect_fn=tf.saved_model.load(PATH_TO_SAVED_MODEL)

Try running steps 17-20 again!

**Comment by ondereser** [comment]
> 'detect_fn' is used in step 17 to load the saved model and build the detection function
> 
> # Load saved model and build the detection function
> detect_fn=tf.saved_model.load(PATH_TO_SAVED_MODEL)
> 
> Try running steps 17-20 again!

Thank you, for your help and great tutorial! 👍
