### ISSUE TITLE
cant move past Step 9

### ISSUE THREAD

**Issue by IrfanAnNaufal** [Nkap23/TensorFlow_with_Colab_tutorial#6]
Hi,
I'm currently stuck at Step 9 which I should run
`!python setup.py build`
`!python setup.py install`

but i get this in return
`python3: can't open file 'setup.py': [Errno 2] No such file or directory`
`python3: can't open file 'setup.py': [Errno 2] No such file or directory`

How or what should i do?

**Comment by Nkap23** [comment]
Hello. The core tensorflow repo was updated. They changed the location of setup.py file. 
I have updated the tutorial and the notebook. 
Try running it now. 

Let me know if the issue persists.

**Comment by IrfanAnNaufal** [comment]
Hi Nkap23, thank you for the fast response. It's working now.
